import json
import re

def generate_intent_contract(user_msg: str, llm_client) -> dict:
    """
    Generates an IntentContract using a hybrid approach.
    Semantic fields are generated by the LLM.
    Deterministic fields are generated heuristically to prevent drift.
    """
    
    # Heuristics for deterministic fields
    requires_tools = True  # We assume tools might be needed by default
    requires_confirmation = False # Core will still block if tool is dangerous
    persistence_policy = "persistent"
    expected_output_type = "action_or_text"
    
    # LLM for semantic fields
    prompt = f"""<|im_start|>system
You are Astra's intent classifier. Your job is to strictly define the semantic objective, constraints, and task category of the user's request.
Output ONLY valid JSON with exactly these three keys:
"objective": A clear, single sentence stating what the user wants to accomplish.
"constraints": An array of strings defining any limitations, scope, or rules to follow.
"task_type": One of: "chat", "tool_request", "memory_operation", "multi_step".

User request: {user_msg}
<|im_end|>
<|im_start|>assistant
"""
    try:
        response = llm_client.generate(prompt)
        
        # Simple extraction
        json_match = re.search(r'\{.*\}', response, re.DOTALL)
        if json_match:
            parsed = json.loads(json_match.group(0))
            objective = parsed.get("objective", user_msg)
            constraints = parsed.get("constraints", [])
            task_type = parsed.get("task_type", "chat")
        else:
            objective = user_msg
            constraints = []
            task_type = "chat"
    except Exception:
        objective = user_msg
        constraints = []
        task_type = "chat"
        
    return {
        "objective": objective,
        "constraints": constraints,
        "task_type": task_type,
        "requires_tools": requires_tools,
        "requires_confirmation": requires_confirmation,
        "persistence_policy": persistence_policy,
        "expected_output_type": expected_output_type
    }
